{"frames":[{"func":"reticulate::py_run_string(\"import certifi; import ssl; ssl.create_default_context = ssl.create_default_context(cafile=certifi.where())\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"py_run_string_impl(code, local, convert)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"stop(structure(list(message = \"TypeError: 'SSLContext' object is not callable\\n\", \n    call = NULL, cppstack = structure(list(file = \"\", line = -1L, \n        stack = c(\"1   reticulate.so                       0x00000001118b97de _ZN4Rcpp9exceptionC2EPKcb + 222\", \n        \"2   reticulate.so                       0x00000001118c1665 _ZN4Rcpp4stopERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 53\",  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error: TypeError: 'SSLContext' object is not callable\n"}